# Using `fpl_data.transform` module

In [1]:
import pandas as pd
from fpl_data.transform import FplApiDataTransformed

pd.set_option('display.max_columns', None)

Load and transform data

In [2]:
data = FplApiDataTransformed()

Getting data from API
...
DONE!

## Players

In [4]:
# get a list of all players as a dataframe
data.players_df.sort_values('Pts', ascending=False)

,team,pos,first_name,second_name,player_name,Â£,ST,MP,Pts,GS,A,GI,xG,xA,xGI,PPG,Pts90,GS90,A90,GI90,xG90,xA90,xGI90,CS,GC,xGC,GC90,xGC90,OG,PS,PM,YC,RC,S,S90,B,BPS,BPS90,I,C,T,II,I90,C90,T90,II90,TSB%
player_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
182,CHE,MID,Cole,Palmer,Palmer,10.5,29,2617,244,22,13,35,17.4,8.2,25.5,7.2,8.4,0.8,0.4,1.2,0.6,0.3,0.9,7,46,45.5,1.6,1.6,0,0,0,7,0,0,0.0,32,844,29.0,1240.2,1022.5,1016.0,327.8,42.7,35.2,34.9,11.3,55.8
348,MCI,MID,Phil,Foden,Foden,9.5,33,2860,230,19,8,27,10.2,7.0,17.1,6.6,7.2,0.6,0.3,0.8,0.3,0.2,0.5,14,27,28.5,0.8,0.9,0,0,0,2,0,0,0.0,31,866,27.3,1154.8,1157.8,1172.0,348.8,36.3,36.4,36.9,11.0,32.5
58,AVL,FWD,Ollie,Watkins,Watkins,9.0,37,3222,228,19,18,37,16.7,4.0,20.8,6.2,6.4,0.5,0.5,1.0,0.5,0.1,0.6,7,56,55.0,1.6,1.5,0,0,0,4,0,0,0.0,29,752,21.0,1024.6,588.5,1420.0,302.8,28.6,16.4,39.7,8.5,56.7
17,ARS,MID,Bukayo,Saka,Saka,10.0,35,2922,226,16,12,28,15.4,10.9,26.3,6.5,7.0,0.5,0.4,0.9,0.5,0.3,0.8,16,27,25.7,0.8,0.8,0,0,0,4,0,0,0.0,29,776,23.9,1093.8,1319.8,1342.0,375.7,33.7,40.7,41.3,11.6,27.1
351,MCI,FWD,Erling,Haaland,Haaland,15.0,29,2553,217,27,8,35,29.6,2.2,31.8,7.0,7.6,1.0,0.3,1.2,1.0,0.1,1.1,11,25,25.6,0.9,0.9,0,0,1,1,0,0,0.0,29,792,27.9,1094.6,367.2,1581.0,303.3,38.6,12.9,55.7,10.7,31.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,LIV,MID,Stefan,BajÄetiÄ Maquieira,Bajcetic,4.5,0,25,1,0,0,0,0.0,0.0,0.0,1.0,3.6,0.0,0.0,0.0,0.0,0.0,0.0,0,2,0.9,7.2,3.2,0,0,0,0,0,0,0.0,0,3,10.8,7.8,0.3,0.0,0.8,28.1,1.1,0.0,2.9,0.2
318,LIV,MID,Ben,Doak,Doak,4.5,0,13,1,0,0,0,0.0,0.0,0.0,1.0,6.9,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.1,0.0,1.0,0,0,0,0,0,0,0.0,0,3,20.8,0.2,0.8,0.0,0.1,1.4,5.5,0.0,0.7,0.1
150,CHE,MID,Andrey,Nascimento dos Santos,Andrey Santos,4.5,0,7,1,0,0,0,0.1,0.0,0.1,1.0,12.9,0.0,0.0,0.0,0.8,0.0,0.8,0,0,0.0,0.0,0.3,0,0,0,0,0,0,0.0,0,1,12.9,0.0,0.5,3.0,0.2,0.0,6.4,38.6,2.6,0.1
49,AVL,DEF,Tyrone,Mings,Mings,4.5,1,30,0,0,0,0,0.0,0.2,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0,2,1.1,6.0,3.2,0,0,0,0,0,0,0.0,0,5,15.0,3.6,13.0,5.0,2.2,10.8,39.0,15.0,6.6,0.5
6,ARS,DEF,JurriÃ«n,Timber,J.Timber,5.5,1,70,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.3,0.0,0.4,0,0,0,2,0,0,0.0,0,4,5.1,5.8,4.7,2.0,1.3,7.5,6.0,2.6,1.7,2.7

## Player summary
The `.get_player_summary()` method can be used to get a player's past or future fixtures

In [7]:
# get the upcoming fixtures for a player
player_fx = data.get_player_summary(355, 'fixtures')
player_fx.head()

Fetching
...
DONE!

   team  difficulty
gw
1   CHE           4
2   IPS           2
3   WHU           2
4   BRE           2
5   ARS           5

We can apply some styling to the result above to get a more graphical representation of the upcoming fixtures' difficulty

In [12]:
def style_background_player_fdr(cell_value):

    bg = 'background-color:'

    if cell_value == 1:
        return f'{bg} darkgreen;'
    elif cell_value == 2:
        return f'{bg} green;'
    elif cell_value == 3:
        return f'{bg} grey;'
    elif cell_value == 4:
        return f'{bg} orange;'
    elif cell_value == 5:
        return f'{bg} darkred;'
    else:
        return ''

# ToDo: make this part of the package
player_fx.head(10).T.style.map(style_background_player_fdr)

In [13]:
# ToDo: handle case when there are no previous fixtures
player_id = 355
data.get_player_summary(player_id, 'history')

Fetching
...
DONE!

KeyError: 'opponent_team'

## Fixtures
Try to create a fixtures matrix, showing each team's upcoming fixtures and their difficulty

In [14]:
fx = data.get_fixtures_matrix()
fx

,1,2,3,4,5,6,7,8,9
team_home,,,,,,,,,
AVL,WHU (A) 2,ARS (H) 5,LEI (A) 2,EVE (H) 2,WOL (H) 2,IPS (A) 2,MUN (H) 3,FUL (A) 3,BOU (H) 2
EVE,BHA (H) 2,TOT (A) 4,BOU (H) 2,AVL (A) 4,LEI (A) 2,CRY (H) 2,NEW (H) 3,IPS (A) 2,FUL (H) 2
NFO,BOU (H) 2,SOU (A) 2,WOL (H) 2,LIV (A) 5,BHA (A) 2,FUL (H) 2,CHE (A) 4,CRY (H) 2,LEI (A) 2
IPS,LIV (H) 4,MCI (A) 5,FUL (H) 2,BHA (A) 2,SOU (A) 2,AVL (H) 3,WHU (A) 2,EVE (H) 2,BRE (A) 2
LIV,IPS (A) 2,BRE (H) 2,MUN (A) 3,NFO (H) 2,BOU (H) 2,WOL (A) 2,CRY (A) 3,CHE (H) 3,ARS (A) 5
MUN,FUL (H) 2,BHA (A) 2,LIV (H) 4,SOU (A) 2,CRY (A) 3,TOT (H) 3,AVL (A) 4,BRE (H) 2,WHU (A) 2
CHE,MCI (H) 5,WOL (A) 2,CRY (H) 2,BOU (A) 2,WHU (A) 2,BHA (H) 2,NFO (H) 2,LIV (A) 5,NEW (H) 3
CRY,BRE (A) 2,WHU (H) 2,CHE (A) 4,LEI (H) 2,MUN (H) 3,EVE (A) 3,LIV (H) 4,NFO (A) 2,TOT (H) 3
LEI,TOT (H) 3,FUL (A) 3,AVL (H) 3,CRY (A) 3,EVE (H) 2,ARS (A) 5,BOU (H) 2,SOU (A) 2,NFO (H) 2
FUL,MUN (A) 3,LEI (H) 2,IPS (A) 2,WHU (H) 2,NEW (H) 3,NFO (A) 2,MCI (A) 5,AVL (H) 3,EVE (A) 3
MCI,CHE (A) 4,IPS (H) 2,WHU (A) 2,BRE (H) 2,ARS (H) 5,NEW (A) 4,FUL (H) 2,WOL (A) 2,SOU (H) 2
TOT,LEI (A) 2,EVE (H) 2,NEW (A) 4,ARS (H) 5,BRE (H) 2,MUN (A) 3,BHA (A) 2,WHU (H) 2,CRY (A) 3
NEW,SOU (H) 2,BOU (A) 2,TOT (H) 3,WOL (A) 2,FUL (A) 3,MCI (H) 5,EVE (A) 3,BHA (H) 2,CHE (A) 4
BRE,CRY (H) 2,LIV (A) 5,SOU (H) 2,MCI (A) 5,TOT (A) 4,WHU (H) 2,WOL (H) 2,MUN (A) 3,IPS (H) 2
SOU,NEW (A) 4,NFO (H) 2,BRE (A) 2,MUN (H) 3,IPS (H) 2,BOU (A) 2,ARS (A) 5,LEI (H) 2,MCI (A) 5
ARS,WOL (H) 2,AVL (A) 4,BHA (H) 2,TOT (A) 4,MCI (A) 5,LEI (H) 2,SOU (H) 2,BOU (A) 2,LIV (H) 4
WHU,AVL (H) 3,CRY (A) 3,MCI (H) 5,FUL (A) 3,CHE (H) 3,BRE (A) 2,IPS (H) 2,TOT (A) 4,MUN (H) 3
BHA,EVE (A) 3,MUN (H) 3,ARS (A) 5,IPS (H) 2,NFO (H) 2,CHE (A) 4,TOT (H) 3,NEW (A) 4,WOL (H) 2
BOU,NFO (A) 2,NEW (H) 3,EVE (A) 3,CHE (H) 3,LIV (A) 5,SOU (H) 2,LEI (A) 2,ARS (H) 5,AVL (A) 4
WOL,ARS (A) 5,CHE (H) 3,NFO (A) 2,NEW (H) 3,AVL (A) 4,LIV (H) 4,BRE (A) 2,MCI (H) 5,BHA (A) 2

In [16]:
def style_background_team_fdr(cell_value):

    bg = 'background-color:'
    team_str = 0

    if cell_value != '':
        team_str = int(cell_value[-1])

    if team_str == 1:
        return f'{bg} darkgreen;'
    elif team_str == 2:
        return f'{bg} green;'
    elif team_str == 3:
        return f'{bg} grey;'
    elif team_str == 4:
        return f'{bg} orange;'
    elif team_str == 5:
        return f'{bg} darkred;'
    else:
        return ''

fx.style.map(style_background_team_fdr)